"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var payment_1 = require("../controllers/payment");
var validate_token_1 = require("./validate-token");
var router = (0, express_1.Router)();
router.post("/create-checkout-session", validate_token_1.default, payment_1.createSession);
router.get('/direccion-envio', payment_1.newEnvio);
router.get("/success", function (req, res) { return res.redirect('http://koliseo.duckdns.org/tienda'); });
router.get("/cancel", function (req, res) { return res.send('http://koliseo.duckdns.org/direccion-envio'); });
exports.default = router;
